### ISSUE TITLE
Can this be run in parallel using multiple cores?

### ISSUE THREAD

**Issue by Cerebrock** [kul-forbes/scs#24]
Using cvxpy in windows server 2012 r2 on Intel Xeon E5 4610 v4 with 10 cores. Or with GPU??

**Comment by rileyjmurray** [comment]
The parallelism in SuperSCS is the same as that of SCS. If you use ``use_gpu=True`` as a keyword argument in cvxpy's ``.solve`` function, then the projection operation will be performed via GPU. Using multiple threads is a slightly more delicate issue: you need to make sure that your (Super)SCS installation was compiled with OpenMP enabled. See https://github.com/cvxgrp/scs/issues/82 for a related discussion.

**Comment by alphaville** [comment]
This is a good point and we should add some examples in the documentation. As rileyjmurray explained, SuperSCS builds on top of SCS and the parallelism is already implemented in SCS.

**Comment by alphaville** [comment]
@Cerebrock I updated the documentation and commented on the use of OpenMP (read [this page](https://kul-forbes.github.io/scs/page_doc.html#sec_compiling_superscs_in_c)). We haven't tested on GPUs yet, but we'll do that soon.
