### ISSUE TITLE
Test with `rho_x<1` and `k0!=1`

### ISSUE THREAD

**Issue by alphaville** [kul-forbes/scs#3]
Test with `rho_x<1` and `k0!=1`.

Make sure that the algorithm works properly with  `rho_x<1`, `k0!=1` and several combinations of `k1`, `k2` and `ls`.

Check (at least) the following:
1. All residuals
2. Number of iterations
3. Solutions (for a limited number of iterations)
4. Status codes

**Comment by KrinaM** [comment]
ok!
